# Generated by Django 3.2.5 on 2021-07-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicS', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-data_added',)},
        ),
    ]
